# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]}
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
end

# ✅ Enable the New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

target 'CTReactNative' do
  config = use_native_modules!

  # ✅ Use static linkage for CocoaPods
  use_frameworks! :linkage => :static

  # ✅ Enable Fabric and Hermes for New Architecture
  use_react_native!(
    :path => config[:reactNativePath],
    :fabric_enabled => true,
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # ✅ Add CleverTap Pods
  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'
  pod 'CleverTap-iOS-SDK'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end